Repository Buddies2024/spring, pull requests merged in 2024-12, with the labels that each got.

#439 일기 작성 페이지 툴팁 박스 추가
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/static/images/diary/write-page/tooltip.png
  src/main/resources/static/js/diary/write-page/write-diary.js
  src/main/resources/templates/diary/write-page.html
Labels: FE, ✨ feat

#441 카카오 id 유니크 제약 조건 추가
  src/main/resources/db/migration/V3.5__add_unique_index_on_kakaoId.sql
Labels: BE, 🛠️ refactor

#444 일기 작성페이지 툴팁, 도움말 버그 수정
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/templates/diary/write-page.html
Labels: FE, 🐞 bug

#443 댓글 구현
  src/main/java/com/exchangediary/comment/ui/dto/request/CommentCreateRequest.java
  src/main/java/com/exchangediary/comment/ui/dto/request/ReplyCreateRequest.java
  src/main/resources/static/css/diary/comment.css
  src/main/resources/static/css/diary/reply.css
  src/main/resources/static/css/diary/sticker.css
  src/main/resources/static/images/diary/view-page/blue-reply-character.png
  src/main/resources/static/images/diary/view-page/comment-arrow.png
  src/main/resources/static/images/diary/view-page/comment-icon.png
  src/main/resources/static/images/diary/view-page/green-reply-character.png
  src/main/resources/static/images/diary/view-page/sticker-icon.png
  src/main/resources/static/images/diary/view-page/sticker/angry-icon.png
  src/main/resources/static/images/diary/view-page/sticker/angry-sticker.png
  src/main/resources/static/images/diary/view-page/sticker/eating-icon.png
  src/main/resources/static/images/diary/view-page/sticker/eating-sticker.png
  src/main/resources/static/images/diary/view-page/sticker/heart-icon.png
  src/main/resources/static/images/diary/view-page/sticker/heart-sticker.png
  src/main/resources/static/images/diary/view-page/sticker/question-icon.png
  src/main/resources/static/images/diary/view-page/sticker/question-sticker.png
  src/main/resources/static/images/diary/view-page/sticker/sad-icon.png
  src/main/resources/static/images/diary/view-page/sticker/sad-sticker.png
  src/main/resources/static/images/diary/view-page/sticker/troubled-icon.png
  src/main/resources/static/images/diary/view-page/sticker/troubled-sticker.png
  src/main/resources/static/images/diary/view-page/sticker/v-sign-icon.png
  src/main/resources/static/images/diary/view-page/sticker/v-sign-sticker.png
  src/main/resources/static/images/diary/view-page/white-comment-icon.png
  src/main/resources/static/images/diary/view-page/white-sticker-icon.png
  src/main/resources/static/images/diary/view-page/yellow-sticker-icon.png
  src/main/resources/static/js/common/modal/confirm-modal.js
  src/main/resources/static/js/diary/view-diary/adjust-comment-height.js
  src/main/resources/static/js/diary/view-diary/click-comment-outside.js
  src/main/resources/static/js/diary/view-diary/comment-textarea.js
  src/main/resources/static/js/diary/view-diary/comment.js
  src/main/resources/static/js/diary/view-diary/draw-comment-character.js
  src/main/resources/static/js/diary/view-diary/draw-comment.js
  src/main/resources/static/js/diary/view-diary/slide-diary.js
  src/main/resources/static/js/diary/view-diary/sticker.js
  src/main/resources/static/js/diary/view-diary/view-diary.js
  src/main/resources/static/js/diary/view-diary/write-comment.js
  src/main/resources/templates/diary/view-page.html
Labels: FE, ✨ feat
