Repository Buddies2024/spring, pull requests merged in 2024-09, with the labels that each got.

#3 [back/feature] static entity 추가
  server/.gitignore
  server/gradlew.bat
  server/src/main/java/com/exchangediary/ExchangediaryApplication.java
  server/src/main/java/com/exchangediary/global/domain/entity/BaseEntity.java
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImageType.java
  server/src/main/resources/application.properties
Labels: BE, ✨ feat

#5 [back/chore] static image에 baseEntity 상속
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
Labels: BE, 🧦 chore

#7 [back/feature] 일기, 업로드 이미지 엔티티 생성
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/domain/entity/PublicationStatus.java
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
Labels: BE, ✨ feat

#8 [back/feature] 스티커 엔티티 생성
  server/src/main/java/com/exchangediary/diary/domain/entity/Sticker.java
Labels: BE, ✨ feat

#10 chore : client 디렉토리 추가
  client/README.md
Labels: 🧦 chore

#17 13 frontfeature navigate 로직 추가
  client/.gitignore
  client/src/global/navi/stackNavigator.tsx
  client/src/global/navi/useStackNavigation.ts
Labels: FE, ✨ feat

#15 [back/feature] 일기, 업로드 이미지 엔티티에 final 타입 및 지연로딩 추가
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
Labels: BE, ✨ feat

#18 [back/feature] StaticImage entity final 수정 및 import 와일드카드 제거
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
Labels: BE, ✨ feat, 🖌️style

#19 Sticker entity final 수정, import 와일드카드 제거, 연관매핑 지연로딩 추가
  server/src/main/java/com/exchangediary/diary/domain/entity/Sticker.java
Labels: BE, ✨ feat

#27 서버 배포 스크립트 구축(임시)
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD

#28 application.yml 환경변수 ver 업로드
  server/src/main/resources/application.yml
Labels: BE, 🚀 CI / CD

#29 배포 스크립트 테스트
  server/src/main/resources/application.yml
Labels: BE, 🚀 CI / CD, 🔎 test

#30 깃허브 가상환경 JDK 설정 추가
  .github/workflows/deploy.yml
Labels: BE, 🐞 bug, 🚀 CI / CD

#31 배포 스크립트 테스트
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD

#32 배포 스크립트 JDK job distribution 누락 해결
  .github/workflows/deploy.yml
Labels: BE, 🐞 bug, 🚀 CI / CD

#33 배포 스크립트 테스트 (JDK 문제 해결)
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD, 🔎 test

#34 배포 스크립트 jdk 지원되는 버전(temurin)으로 수정
  .github/workflows/deploy.yml
Labels: BE, 🐞 bug, 🚀 CI / CD

#36 배포 스크립트 테스트
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD, 🔎 test

#37 깃허브 액션 환경변수 등록
  .github/workflows/deploy.yml
Labels: BE, 🐞 bug, 🚀 CI / CD

#38 배포 스크립트 테스트
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD

#44 feat: 일기 업로드 모달 추가 및 달력형 페이지 추가 (#35)
  client/src/pages/dateDiary/dataDiary.js
  client/src/pages/editdiary/asset/backButton.png
  client/src/pages/editdiary/asset/background.png
  client/src/pages/editdiary/asset/bookmark.png
  client/src/pages/editdiary/asset/funny.png
  client/src/pages/editdiary/components/outputModal.js
  client/src/pages/editdiary/components/topButton.js
  client/src/pages/editdiary/diaryScreen.js
Labels: FE, ✨ feat

#51 일기 상세 조회 API 개발
  .DS_Store
  server/.gitignore
  server/src/main/java/com/exchangediary/diary/domain/UploadImageRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/domain/entity/DiaryRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/StickerRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDetailResponse.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDetailStickerResponse.java
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
  server/src/main/java/com/exchangediary/global/service/ImageService.java
  server/src/main/java/com/exchangediary/global/ui/StaticImageController.java
  server/src/main/java/com/exchangediary/global/util/DateTimeUtil.java
Labels: BE, ✨ feat

#53 일기작성 페이지 글작성영역 생성,
  client/package.json
  client/src/pages/editdiary/diaryScreen.js
Labels: FE, ✨ feat

#54 이미지 삽입 구현 및 위치 수정
  client/src/pages/editdiary/asset/backButton.png
  client/src/pages/editdiary/asset/bookmark.png
  client/src/pages/editdiary/components/imageModal.js
  client/src/pages/editdiary/diaryScreen.js
Labels: FE, ✨ feat

#58 일기 상세 조회, 스티커 목록 조회 배포
  .DS_Store
  client/package.json
  client/src/pages/dateDiary/dataDiary.js
  client/src/pages/editdiary/asset/background.png
  client/src/pages/editdiary/asset/funny.png
  client/src/pages/editdiary/components/imageModal.js
  client/src/pages/editdiary/components/outputModal.js
  client/src/pages/editdiary/components/topButton.js
  client/src/pages/editdiary/diaryScreen.js
  server/.gitignore
  server/src/main/java/com/exchangediary/diary/domain/UploadImageRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/domain/entity/DiaryRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/StickerRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDetailResponse.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDetailStickerResponse.java
  server/src/main/java/com/exchangediary/global/domain/StaticImageRepository.java
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
  server/src/main/java/com/exchangediary/global/service/ImageService.java
  server/src/main/java/com/exchangediary/global/service/StaticImageQueryService.java
  server/src/main/java/com/exchangediary/global/ui/StaticImageController.java
  server/src/main/java/com/exchangediary/global/ui/dto/response/StaticImageResponse.java
  server/src/main/java/com/exchangediary/global/ui/dto/response/StickersResponse.java
  server/src/main/java/com/exchangediary/global/util/DateTimeUtil.java
Labels: BE, 🚀 CI / CD

#60 깃허브 액션스 jar 복사 방식 수정
  .github/workflows/deploy.yml
Labels: BE, 🐞 bug, 🚀 CI / CD

#61 배포 스크립트 공백 수정
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD

#62 배포 스크립트 수정 및 재배포
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD

#63 배포 스크립트 scp 다른 방식으로 시도
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD

#64 배포 스크립스 수정 및 재배포
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD

#65 배포 스크립트 수정
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD

#66 서버 배포
  .github/workflows/deploy.yml
Labels: BE, 🚀 CI / CD

#52 기분 목록 조회 API 개발
  server/src/main/java/com/exchangediary/global/service/StaticImageQueryService.java
  server/src/main/java/com/exchangediary/global/ui/StaticImageController.java
  server/src/main/java/com/exchangediary/global/ui/dto/response/MoodsResponse.java
Labels: BE, ✨ feat

#56 스티커 붙이기 API 개발
  server/build.gradle
  server/src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  server/src/main/java/com/exchangediary/diary/domain/StickerRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/Sticker.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/service/StickerCommandService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/StickerRequest.java
  server/src/main/java/com/exchangediary/global/domain/entity/ErrorCode.java
  server/src/main/java/com/exchangediary/global/domain/entity/NotFoundException.java
  server/src/main/java/com/exchangediary/global/ui/GlobalExceptionHandler.java
  server/src/main/java/com/exchangediary/global/ui/dto/response/ErrorResponse.java
Labels: BE, ✨ feat

#68 기분 목록 조회 API, 스티커 붙이기 API 배포
  server/build.gradle
  server/src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  server/src/main/java/com/exchangediary/diary/domain/StickerRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/Sticker.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/service/StickerCommandService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/StickerRequest.java
  server/src/main/java/com/exchangediary/global/domain/entity/ErrorCode.java
  server/src/main/java/com/exchangediary/global/domain/entity/NotFoundException.java
  server/src/main/java/com/exchangediary/global/service/StaticImageQueryService.java
  server/src/main/java/com/exchangediary/global/ui/GlobalExceptionHandler.java
  server/src/main/java/com/exchangediary/global/ui/StaticImageController.java
  server/src/main/java/com/exchangediary/global/ui/dto/response/ErrorResponse.java
  server/src/main/java/com/exchangediary/global/ui/dto/response/MoodsResponse.java
Labels: BE, 🚀 CI / CD

#67 이미지 삽입 구현 완료 및 텍스트 입력란 레이아웃 완료
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/pages/editdiary/components/imageModal.js
  client/src/pages/editdiary/components/textModal.js
  client/src/pages/editdiary/diaryScreen.js
Labels: FE, ✨ feat, 🖌️style

#57 일기 작성 API 개발
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/DiaryRequest.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/UploadImageRequest.java
  server/src/main/java/com/exchangediary/global/domain/entity/ErrorCode.java
  server/src/main/java/com/exchangediary/global/domain/entity/ImageUploadException.java
  server/src/main/java/com/exchangediary/global/service/ImageService.java
  server/src/main/java/com/exchangediary/global/ui/GlobalExceptionHandler.java
Labels: BE, ✨ feat

#71 일기 상세 조회 예외처리 추가, exception 패키지 분리
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/service/StickerCommandService.java
  server/src/main/java/com/exchangediary/global/domain/entity/ErrorCode.java
  server/src/main/java/com/exchangediary/global/domain/entity/ImageUploadException.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/ErrorResponse.java
  server/src/main/java/com/exchangediary/global/exception/GlobalException.java
  server/src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
Labels: BE, ✨ feat

#74 일기 작성 api 예외처리 수정
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/global/domain/entity/ImageUploadException.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
Labels: BE, 🛠️ refactor

#75 정적 이미지 업로드 API 개발
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
  server/src/main/java/com/exchangediary/global/service/StaticImageCommandService.java
  server/src/main/java/com/exchangediary/global/ui/StaticImageController.java
  server/src/main/java/com/exchangediary/global/ui/dto/request/StaticImageUploadRequest.java
Labels: BE, ✨ feat

#76 API 예외처리 수정, 정적 이미지 업로드 API 개발 후 배포
  client/.gitignore
  client/package-lock.json
  client/package.json
  client/src/pages/editdiary/components/imageModal.js
  client/src/pages/editdiary/components/textModal.js
  client/src/pages/editdiary/diaryScreen.js
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/service/StickerCommandService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/DiaryRequest.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/UploadImageRequest.java
  server/src/main/java/com/exchangediary/global/domain/entity/ErrorCode.java
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/ErrorResponse.java
  server/src/main/java/com/exchangediary/global/exception/GlobalException.java
  server/src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  server/src/main/java/com/exchangediary/global/service/ImageService.java
  server/src/main/java/com/exchangediary/global/service/StaticImageCommandService.java
  server/src/main/java/com/exchangediary/global/ui/StaticImageController.java
  server/src/main/java/com/exchangediary/global/ui/dto/request/StaticImageUploadRequest.java
Labels: BE, 🚀 CI / CD

#77 월별형 조회 api 개발
  server/src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
Labels: BE, ✨ feat

#78 월별형 조회 API 개발 후 배포
  server/src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
Labels: BE, 🚀 CI / CD

#81 기분목록조회 이미지url null로 나오는 문제 해결
  server/src/main/java/com/exchangediary/global/service/ImageService.java
Labels: BE, 🐞 bug

#82 정적이미지등록 버그 수정 후 재배포
  server/src/main/java/com/exchangediary/global/service/ImageService.java
Labels: BE, 🚀 CI / CD

#84 sticker 엔티티 오류 해결
  server/src/main/java/com/exchangediary/diary/domain/entity/Sticker.java
Labels: BE, 🐞 bug, 🖌️style

#90 일기 API 보완
  server/src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryIdResponse.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
Labels: BE, ✨ feat

#97 일기 작성 및 조회 API 수정
  server/src/main/java/com/exchangediary/diary/domain/StickerRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/domain/entity/PublicationStatus.java
  server/src/main/java/com/exchangediary/diary/domain/entity/Sticker.java
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/service/StickerCommandService.java
  server/src/main/java/com/exchangediary/diary/service/UploadImageService.java
  server/src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/DiaryRequest.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/StickerRequest.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/UploadImageRequest.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDetailResponse.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDetailStickerResponse.java
  server/src/main/java/com/exchangediary/global/domain/StaticImageRepository.java
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImage.java
  server/src/main/java/com/exchangediary/global/domain/entity/StaticImageType.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/service/ImageService.java
  server/src/main/java/com/exchangediary/global/service/StaticImageCommandService.java
  server/src/main/java/com/exchangediary/global/service/StaticImageQueryService.java
  server/src/main/java/com/exchangediary/global/ui/StaticImageController.java
  server/src/main/java/com/exchangediary/global/ui/dto/request/StaticImageUploadRequest.java
  server/src/main/java/com/exchangediary/global/ui/dto/response/MoodsResponse.java
  server/src/main/java/com/exchangediary/global/ui/dto/response/StaticImageResponse.java
  server/src/main/java/com/exchangediary/global/ui/dto/response/StickersResponse.java
Labels: BE, ✨ feat

#116 카카오 로그인 구현(사용자 로그인 처리 부분 제외)
  .gitignore
  server/build.gradle
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/service/UploadImageService.java
  server/src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  server/src/main/java/com/exchangediary/global/exception/ApiErrorResponse.java
  server/src/main/java/com/exchangediary/global/exception/DiaryNotFoundException.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/ErrorResponse.java
  server/src/main/java/com/exchangediary/global/exception/FailedImageUploadException.java
  server/src/main/java/com/exchangediary/global/exception/GlobalException.java
  server/src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  server/src/main/java/com/exchangediary/global/exception/InvalidDateException.java
  server/src/main/java/com/exchangediary/global/exception/InvalidRangeException.java
  server/src/main/java/com/exchangediary/global/exception/KakaoLoginFailureException.java
  server/src/main/java/com/exchangediary/global/exception/KakaoTokenFailureException.java
  server/src/main/java/com/exchangediary/global/exception/KakaoUserFailureException.java
  server/src/main/java/com/exchangediary/global/exception/NotFoundException.java
  server/src/main/java/com/exchangediary/global/exception/ServiceException.java
  server/src/main/java/com/exchangediary/global/exception/UploadImageNotFoundException.java
  server/src/main/java/com/exchangediary/member/service/KakaoService.java
  server/src/main/java/com/exchangediary/member/ui/KakaoLoginController.java
  server/src/main/java/com/exchangediary/member/ui/dto/request/KakaoTokenRequest.java
  server/src/main/java/com/exchangediary/member/ui/dto/response/KakaoIdResponse.java
  server/src/main/java/com/exchangediary/member/ui/dto/response/KakaoTokenResponse.java
  server/src/main/resources/application.yml
  server/src/main/resources/static/images/background.svg
  server/src/main/resources/static/js/calendar-arrow.js
  server/src/main/resources/static/js/draw-calendar.js
  server/src/main/resources/templates/index.html
Labels: BE, ✨ feat

#115 예외 클래스 계층화 및 리팩터링
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/service/UploadImageService.java
  server/src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  server/src/main/java/com/exchangediary/global/exception/ApiErrorResponse.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/ErrorResponse.java
  server/src/main/java/com/exchangediary/global/exception/GlobalException.java
  server/src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/ServiceException.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/internalservererror/FailedImageUploadException.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/invliadrange/DateRangeException.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/invliadrange/InvalidRangeException.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/notfound/DiaryNotFoundException.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/notfound/NotFoundException.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/notfound/UploadImageNotFoundException.java
Labels: BE, 🛠️ refactor

#119 회원가입 및 로그인 서비스 개발
  server/src/main/java/com/exchangediary/member/domain/MemberRepository.java
  server/src/main/java/com/exchangediary/member/domain/entity/Member.java
  server/src/main/java/com/exchangediary/member/service/MemberRegistrationService.java
  server/src/main/java/com/exchangediary/member/ui/KakaoLoginController.java
  server/src/main/java/com/exchangediary/member/ui/dto/response/MemberIdResponse.java
Labels: BE, ✨ feat

#118 일기 작성 하루에 여러 번 가능한 오류 해결
  server/src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/duplicate/DiaryDuplicateException.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/duplicate/DuplicateException.java
Labels: BE, 🐞 bug

#121 OAuth 카카오 로그인, 회원 생성 개발
  server/build.gradle
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/internalservererror/KakaoLoginFailureException.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/internalservererror/KakaoTokenFailureException.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/internalservererror/KakaoUserFailureException.java
  server/src/main/java/com/exchangediary/member/domain/MemberRepository.java
  server/src/main/java/com/exchangediary/member/domain/entity/Member.java
  server/src/main/java/com/exchangediary/member/service/KakaoService.java
  server/src/main/java/com/exchangediary/member/service/MemberRegistrationService.java
  server/src/main/java/com/exchangediary/member/ui/KakaoLoginController.java
  server/src/main/java/com/exchangediary/member/ui/dto/request/KakaoTokenRequest.java
  server/src/main/java/com/exchangediary/member/ui/dto/response/KakaoIdResponse.java
  server/src/main/java/com/exchangediary/member/ui/dto/response/KakaoTokenResponse.java
  server/src/main/java/com/exchangediary/member/ui/dto/response/MemberIdResponse.java
  server/src/test/java/com/exchangediary/member/KakaoLoginTest.java
Labels: BE, ✨ feat

#122 그룹 생성 개발
  server/src/main/java/com/exchangediary/group/domain/GroupRepository.java
  server/src/main/java/com/exchangediary/group/domain/entity/Group.java
  server/src/main/java/com/exchangediary/group/service/GroupCommandService.java
Labels: BE, ✨ feat

#123 그룹 코드 생성
  server/src/main/java/com/exchangediary/group/service/GroupCodeService.java
  server/src/main/java/com/exchangediary/group/service/GroupCommandService.java
Labels: BE, ✨ feat

#125 사용자 엔티티 그룹 관련 필드 추가
  server/src/main/java/com/exchangediary/member/domain/entity/Member.java
Labels: BE, ✨ feat
