Repository Buddies2024/spring, pull requests merged in 2024-10, with the labels that each got.

#138 일기 조회 API 수정
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDetailResponse.java
  server/src/main/java/com/exchangediary/global/util/DateTimeUtil.java
Labels: BE, 🐞 bug

#141 그룹 코드 유효성 검증 API 개발
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/notfound/GroupNotFoundException.java
  server/src/main/java/com/exchangediary/group/domain/GroupRepository.java
  server/src/main/java/com/exchangediary/group/service/GroupCodeService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/group/ui/dto/request/GroupCodeRequest.java
  server/src/main/java/com/exchangediary/group/ui/dto/response/GroupIdResponse.java
  server/src/test/java/com/exchangediary/group/GroupCodeServiceTest.java
  server/src/test/java/com/exchangediary/group/GroupCodeTest.java
Labels: BE, ✨ feat, 🔎 test

#120 월별형 페이지 폰트 적용
  server/src/main/resources/static/css/fonts.css
  server/src/main/resources/static/css/monthly-page.css
  server/src/main/resources/static/images/background.svg
  server/src/main/resources/templates/index.html
Labels: FE, ✨ feat

#148 일기 조회 및 작성 API 수정
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/request/DiaryRequest.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDetailResponse.java
Labels: BE, 🐞 bug, ✨ feat

#149 그룹 생성 API 개발
  server/src/main/java/com/exchangediary/group/domain/entity/Group.java
  server/src/main/java/com/exchangediary/group/service/GroupCommandService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/group/ui/dto/request/GroupNameRequest.java
  server/src/main/java/com/exchangediary/group/ui/dto/response/GroupIdResponse.java
  server/src/test/java/com/exchangediary/group/GroupCodeServiceTest.java
  server/src/test/java/com/exchangediary/group/GroupCodeTest.java
  server/src/test/java/com/exchangediary/group/GroupCommandServiceTest.java
  server/src/test/java/com/exchangediary/group/GroupCreateTest.java
Labels: BE, ✨ feat, 🔎 test

#150 그룹내 선택 프로필 이미지 조회 API 개발
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/ConfilctException.java
  server/src/main/java/com/exchangediary/group/domain/entity/Group.java
  server/src/main/java/com/exchangediary/group/service/GroupQueryService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/group/ui/dto/response/GroupProfileResponse.java
  server/src/main/java/com/exchangediary/member/domain/MemberRepository.java
  server/src/test/java/com/exchangediary/group/GroupCommandServiceTest.java
  server/src/test/java/com/exchangediary/group/GroupProfileTest.java
Labels: BE, ✨ feat, 🔎 test

#154 그룹 정보 조회 서비스 구현
  server/src/main/java/com/exchangediary/group/service/GroupCodeService.java
  server/src/main/java/com/exchangediary/group/service/GroupQueryService.java
  server/src/main/java/com/exchangediary/group/ui/dto/response/GroupMembersResponse.java
  server/src/main/java/com/exchangediary/member/domain/MemberRepository.java
  server/src/test/java/com/exchangediary/group/api/GroupCodeApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
  server/src/test/java/com/exchangediary/group/service/GroupCodeServiceTest.java
  server/src/test/java/com/exchangediary/group/service/GroupCommandServiceTest.java
  server/src/test/java/com/exchangediary/group/service/GroupQueryServiceTest.java
  server/src/test/java/com/exchangediary/member/KakaoLoginTest.java
  server/src/test/java/com/exchangediary/member/domain/MemberRepositoryUnitTest.java
  server/src/test/resources/truncate.sql
Labels: BE, ✨ feat, 🔎 test

#155 닉네임 유효성 검증 API 개발
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/group/service/GroupQueryService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/group/ui/dto/request/GroupNicknameRequest.java
  server/src/main/java/com/exchangediary/group/ui/dto/response/GroupNicknameVerifyResponse.java
  server/src/main/java/com/exchangediary/member/domain/MemberRepository.java
  server/src/test/java/com/exchangediary/group/GroupNicknameTest.java
Labels: BE, ✨ feat, 🔎 test

#162 일기 작성 및 조회 페이지 구현
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryResponse.java
  server/src/main/resources/static/css/diary-common.css
  server/src/main/resources/static/css/write-page.css
  server/src/main/resources/static/images/monthly-page/background.svg
  server/src/main/resources/static/images/view-page/background.svg
  server/src/main/resources/static/images/write-page/back_icon.svg
  server/src/main/resources/static/images/write-page/background.svg
  server/src/main/resources/static/images/write-page/emoji/beam.svg
  server/src/main/resources/static/images/write-page/emoji/bigsmile.svg
  server/src/main/resources/static/images/write-page/emoji/calm.svg
  server/src/main/resources/static/images/write-page/emoji/disgust.svg
  server/src/main/resources/static/images/write-page/emoji/dislike.svg
  server/src/main/resources/static/images/write-page/emoji/dizzy.svg
  server/src/main/resources/static/images/write-page/emoji/funny.svg
  server/src/main/resources/static/images/write-page/emoji/happy.svg
  server/src/main/resources/static/images/write-page/emoji/hate.svg
  server/src/main/resources/static/images/write-page/emoji/hilarious.svg
  server/src/main/resources/static/images/write-page/emoji/panic.svg
  server/src/main/resources/static/images/write-page/emoji/sleepy.svg
  server/src/main/resources/static/images/write-page/emoji/smirk.svg
  server/src/main/resources/static/images/write-page/emoji/soso.svg
  server/src/main/resources/static/images/write-page/emoji/sunglasses.svg
  server/src/main/resources/static/images/write-page/emoji/surprise.svg
  server/src/main/resources/static/images/write-page/emoji/vexation.svg
  server/src/main/resources/static/images/write-page/emoji/wink.svg
  server/src/main/resources/static/images/write-page/modal/background.svg
  server/src/main/resources/static/images/write-page/modal/camera_icon.svg
  server/src/main/resources/static/images/write-page/modal/photo_icon.svg
  server/src/main/resources/static/images/write-page/mood_icon.svg
  server/src/main/resources/static/images/write-page/photo_icon.svg
  server/src/main/resources/static/images/write-page/success_background.svg
  server/src/main/resources/static/images/write-page/test.png
  server/src/main/resources/static/images/write-page/write_icon.svg
  server/src/main/resources/static/js/monthly-page/calendar-arrow.js
  server/src/main/resources/static/js/monthly-page/draw-calendar.js
  server/src/main/resources/static/js/view-diary/draw-diary.js
  server/src/main/resources/static/js/write-page/modal.js
  server/src/main/resources/static/js/write-page/sync-textarea.js
  server/src/main/resources/static/js/write-page/write-diary.js
  server/src/main/resources/templates/index.html
  server/src/main/resources/templates/view-diary.html
  server/src/main/resources/templates/write-page.html
Labels: FE, ✨ feat

#156 스키마 리팩터링
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/diary/service/UploadImageService.java
  server/src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  server/src/main/java/com/exchangediary/group/domain/entity/Group.java
  server/src/main/java/com/exchangediary/member/domain/entity/Member.java
  server/src/main/resources/schema.sql
  server/src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java
  server/src/test/java/com/exchangediary/group/api/GroupNicknameApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
  server/src/test/java/com/exchangediary/group/service/GroupQueryServiceTest.java
  server/src/test/java/com/exchangediary/member/domain/MemberRepositoryUnitTest.java
  server/src/test/resources/images/test.jpg
Labels: BE, 🛠️ refactor

#165 업로드 이미지 엔티티 수정
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
Labels: BE, 🐞 bug

#159 그룹 가입 API 개발
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/group/domain/entity/Group.java
  server/src/main/java/com/exchangediary/group/service/GroupCommandService.java
  server/src/main/java/com/exchangediary/group/service/GroupQueryService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/group/ui/dto/request/GroupJoinRequest.java
  server/src/main/java/com/exchangediary/group/ui/dto/response/GroupJoinResponse.java
  server/src/main/java/com/exchangediary/member/domain/MemberRepository.java
  server/src/main/java/com/exchangediary/member/domain/entity/Member.java
  server/src/main/java/com/exchangediary/member/service/MemberRegistrationService.java
  server/src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
Labels: BE, ✨ feat, 🔎 test

#166 jwt 기반 인증 구현
  server/build.gradle
  server/src/main/java/com/exchangediary/global/config/web/WebConfig.java
  server/src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  server/src/main/java/com/exchangediary/global/exception/serviceexception/UnauthorizedException.java
  server/src/main/java/com/exchangediary/member/service/JwtService.java
  server/src/main/java/com/exchangediary/member/ui/KakaoLoginController.java
  server/src/main/java/com/exchangediary/member/ui/dto/response/JwtTokenResponse.java
  server/src/test/java/com/exchangediary/group/api/GroupCodeApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupNicknameApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
  server/src/test/java/com/exchangediary/member/KakaoLoginTest.java
  server/src/test/java/com/exchangediary/member/service/JwtServiceTest.java
Labels: BE, ✨ feat, 🔎 test

#169 jwt 인증 인터셉터 수정
  server/src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
Labels: BE, 🛠️ refactor

#171 업로드 이미지 엔티티 오류 해결
  server/src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
Labels: BE, 🐞 bug

#175 테스트코드 리팩토링
  server/src/test/java/com/exchangediary/ApiBaseTest.java
  server/src/test/java/com/exchangediary/group/api/GroupCodeApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupNicknameApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
  server/src/test/java/com/exchangediary/group/service/GroupCodeServiceTest.java
  server/src/test/java/com/exchangediary/group/service/GroupCommandServiceTest.java
  server/src/test/java/com/exchangediary/group/service/GroupQueryServiceTest.java
  server/src/test/resources/truncate.sql
Labels: BE, 🛠️ refactor, 🔎 test

#181 jwt 통신 방식 수정
  server/src/main/java/com/exchangediary/global/config/web/WebConfig.java
  server/src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/member/service/CookieService.java
  server/src/main/java/com/exchangediary/member/ui/KakaoLoginController.java
  server/src/main/java/com/exchangediary/member/ui/dto/response/JwtTokenResponse.java
  server/src/test/java/com/exchangediary/group/api/GroupCodeApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupNicknameApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
  server/src/test/java/com/exchangediary/member/KakaoLoginTest.java
  server/src/test/java/com/exchangediary/member/service/CookieServiceTest.java
Labels: BE, ✨ feat

#158 달력형 페이지에 수정 디자인 반영
  server/src/main/resources/static/css/monthly-page.css
  server/src/main/resources/static/images/monthly-page/background.svg
  server/src/main/resources/static/js/monthly-page/calendar-arrow.js
  server/src/main/resources/templates/index.html
Labels: FE, ✨ feat

#160 로그인 페이지 구현
  server/src/main/java/com/exchangediary/member/ui/LoginController.java
  server/src/main/resources/static/css/login.css
  server/src/main/resources/static/images/login-page/background.svg
  server/src/main/resources/static/images/login-page/kakao.svg
  server/src/main/resources/static/images/login-page/spring.svg
  server/src/main/resources/templates/login.html
Labels: FE, ✨ feat

#183 그룹 생성 및 가입 페이지 공통 부분 구현
  server/src/main/java/com/exchangediary/group/ui/GroupController.java
  server/src/main/resources/static/css/group-page.css
  server/src/main/resources/static/images/common/back_icon.svg
  server/src/main/resources/static/images/group/background.svg
  server/src/main/resources/static/images/group/logo.svg
  server/src/main/resources/static/images/group/note.svg
  server/src/main/resources/static/images/group/step1.svg
  server/src/main/resources/templates/diary/view-diary.html
  server/src/main/resources/templates/diary/write-page.html
  server/src/main/resources/templates/group-page.html
Labels: FE, ✨ feat

#187 그룹 생성 및 가입 페이지 공통 부분 리팩터링
  server/src/main/resources/static/css/group/group-common.css
  server/src/main/resources/templates/group-page.html
Labels: FE, 🛠️ refactor

#177 그룹 생성 시 그룹 생성한 멤버와 매핑 추가
  server/src/main/java/com/exchangediary/group/service/GroupCommandService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/member/domain/entity/Member.java
  server/src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
  server/src/test/java/com/exchangediary/group/service/GroupCommandServiceTest.java
Labels: BE, ✨ feat, 🔎 test

#182 그룹 가입, 그룹 닉네임 검증, 그룹 프로필 조회 API 사용자 인증 추가
  server/src/main/java/com/exchangediary/group/service/GroupCommandService.java
  server/src/main/java/com/exchangediary/group/service/GroupQueryService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/member/domain/MemberRepository.java
  server/src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
Labels: BE, ✨ feat, 🔎 test

#188 인증 실패 및 로그인 성공 시 리다이렉션 추가
  server/src/main/java/com/exchangediary/global/config/web/WebConfig.java
  server/src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
  server/src/main/java/com/exchangediary/member/service/CookieService.java
  server/src/main/java/com/exchangediary/member/service/JwtService.java
  server/src/main/java/com/exchangediary/member/ui/KakaoLoginController.java
  server/src/test/java/com/exchangediary/member/service/JwtServiceTest.java
Labels: BE, ✨ feat

#190 인증 인터셉터 수정 및 그룹 서비스 구조 리팩터링
  server/src/main/java/com/exchangediary/global/config/web/WebConfig.java
  server/src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
  server/src/main/java/com/exchangediary/global/exception/ErrorCode.java
  server/src/main/java/com/exchangediary/group/service/GroupCodeService.java
  server/src/main/java/com/exchangediary/group/service/GroupCommandService.java
  server/src/main/java/com/exchangediary/group/service/GroupCreateService.java
  server/src/main/java/com/exchangediary/group/service/GroupJoinService.java
  server/src/main/java/com/exchangediary/group/service/GroupQueryService.java
  server/src/main/java/com/exchangediary/group/service/GroupValidationService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/member/service/MemberQueryService.java
Labels: BE, 🛠️ refactor

#194 그룹 생성 API 수정
  server/src/main/java/com/exchangediary/group/service/GroupCreateService.java
  server/src/main/java/com/exchangediary/group/service/GroupJoinService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/group/ui/dto/request/GroupCreateRequest.java
  server/src/main/java/com/exchangediary/group/ui/dto/request/GroupNameRequest.java
  server/src/main/java/com/exchangediary/group/ui/dto/response/GroupCreateResponse.java
  server/src/main/java/com/exchangediary/group/ui/dto/response/GroupIdResponse.java
  server/src/main/java/com/exchangediary/member/domain/entity/Member.java
  server/src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
Labels: BE, ✨ feat, 🔎 test

#196 프로필 이미지 선택 조회 API 수정
  server/src/main/java/com/exchangediary/group/service/GroupQueryService.java
  server/src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
Labels: BE, ✨ feat, 🔎 test

#197 그룹 가입 api 수정
  server/src/main/java/com/exchangediary/group/service/GroupJoinService.java
  server/src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  server/src/main/java/com/exchangediary/group/ui/dto/response/GroupJoinResponse.java
  server/src/main/java/com/exchangediary/member/domain/entity/Member.java
  server/src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
Labels: BE, ✨ feat, 🔎 test

#191 일기 작성 성공시 뜨는 화면 구현
  server/src/main/resources/static/css/diary/modal.css
  server/src/main/resources/static/css/notification-modal.css
  server/src/main/resources/static/images/common/notification-modal/background.svg
  server/src/main/resources/static/images/common/notification-modal/error.svg
  server/src/main/resources/static/images/common/notification-modal/success.svg
  server/src/main/resources/static/js/common/image-preloading.js
  server/src/main/resources/static/js/common/notification-modal/modal.js
  server/src/main/resources/static/js/diary/write-page/write-diary.js
  server/src/main/resources/templates/base.html
  server/src/main/resources/templates/common/notification-modal.html
  server/src/main/resources/templates/diary/write-page.html
Labels: FE, ✨ feat

#199 그룹 가입/생성 step1 구현
  server/src/main/resources/static/css/group/group-common.css
  server/src/main/resources/static/css/group/group-step1.css
  server/src/main/resources/static/images/group/group_create.svg
  server/src/main/resources/static/images/group/group_create_white.svg
  server/src/main/resources/static/images/group/group_join.svg
  server/src/main/resources/static/images/group/group_join_white.svg
  server/src/main/resources/static/js/group/group-common.js
  server/src/main/resources/static/js/group/group-step1.js
  server/src/main/resources/templates/group-page.html
Labels: FE, ✨ feat

#201 그룹 가입/생성 step4 구현
  server/src/main/resources/static/css/group/group-step4.css
  server/src/main/resources/static/images/group/step4.svg
  server/src/main/resources/static/js/group/group-common.js
  server/src/main/resources/static/js/group/group-step4.js
  server/src/main/resources/templates/group-page.html
Labels: FE, ✨ feat

#186 일기 API에 사용자, 그룹 도입. 테스트 코드 구현
  server/src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  server/src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  server/src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  server/src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
  server/src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
  server/src/test/java/com/exchangediary/diary/api/DiaryFindIdApiTest.java
  server/src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
  server/src/test/java/com/exchangediary/group/api/GroupNicknameApiTest.java
  server/src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
Labels: BE, ✨ feat, 🔎 test

#198 일기 조회 서비스 수정: 사용자, 그룹 개념 도입, 테스트 코드 구현
  server/src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  server/src/test/java/com/exchangediary/diary/service/DiaryQueryServiceTest.java
Labels: BE, ✨ feat, 🔎 test

#205 그룹 가입/생성 step3 구현
  server/src/main/resources/static/css/group/group-common.css
  server/src/main/resources/static/css/group/group-step3.css
  server/src/main/resources/static/images/group/character/gray-pring1.svg
  server/src/main/resources/static/images/group/character/gray-pring2.svg
  server/src/main/resources/static/images/group/character/gray-pring3.svg
  server/src/main/resources/static/images/group/character/gray-pring4.svg
  server/src/main/resources/static/images/group/character/gray-pring5.svg
  server/src/main/resources/static/images/group/character/gray-pring6.svg
  server/src/main/resources/static/images/group/character/gray-pring7.svg
  server/src/main/resources/static/images/group/character/pring1.svg
  server/src/main/resources/static/images/group/character/pring2.svg
  server/src/main/resources/static/images/group/character/pring3.svg
  server/src/main/resources/static/images/group/character/pring4.svg
  server/src/main/resources/static/images/group/character/pring5.svg
  server/src/main/resources/static/images/group/character/pring6.svg
  server/src/main/resources/static/images/group/character/pring7.svg
  server/src/main/resources/static/images/group/character/select-border.svg
  server/src/main/resources/static/images/group/step3.svg
  server/src/main/resources/static/js/group/group-common.js
  server/src/main/resources/static/js/group/group-step3.js
  server/src/main/resources/templates/group-page.html
Labels: FE, ✨ feat

#206 스프린트1에 그룹, 사용자 도입 된 api 반영
  server/src/main/resources/static/js/diary/write-page/write-diary.js
  server/src/main/resources/static/js/monthly-page/draw-calendar.js
Labels: FE, ✨ feat

#208 그룹 가입/생성 step3 구현
  server/src/main/resources/static/css/group/group-step3.css
  server/src/main/resources/static/js/group/group-step3.js
Labels: FE, 🐞 bug

#202 그룹 가입/생성 step5 구현
  server/src/main/resources/static/css/group/group-step5.css
  server/src/main/resources/static/images/group/heart.svg
  server/src/main/resources/static/js/group/group-common.js
  server/src/main/resources/static/js/group/group-step4.js
  server/src/main/resources/static/js/group/group-step5.js
  server/src/main/resources/templates/group-page.html
Labels: FE, ✨ feat

#221 서버 배포시 타임리프에서 경로 찾지 못한 오류
  server/src/main/resources/templates/base.html
  server/src/main/resources/templates/diary/view-diary.html
  server/src/main/resources/templates/diary/write-page.html
  server/src/main/resources/templates/group-page.html
  server/src/main/resources/templates/index.html
  server/src/main/resources/templates/login.html
Labels: FE, 🐞 bug

#224 다이어리 컨트롤러 반환 파일 경로 수정
  server/src/main/java/com/exchangediary/diary/ui/DiaryController.java
Labels: BE, 🐞 bug

#227 실패 테스트 해결
  src/test/java/com/exchangediary/member/api/LoginApiTest.java
  src/test/java/com/exchangediary/member/service/ExpiredJwtTest.java
  src/test/java/com/exchangediary/member/service/JwtServiceTest.java
  src/test/java/com/exchangediary/member/service/MemberRegistrationServiceTest.java
Labels: BE, 🐞 bug, 🔎 test

#228 시작 페이지 구현
  src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
  src/main/java/com/exchangediary/member/ui/HomeController.java
  src/main/resources/static/css/fonts.css
  src/main/resources/static/css/start.css
  src/main/resources/static/images/start-page/background.svg
  src/main/resources/static/images/start-page/line.gif
  src/main/resources/static/images/start-page/logo.png
  src/main/resources/static/js/start-page/start.js
  src/main/resources/templates/start.html
Labels: FE, ✨ feat

#219 일기 작성 api Location 헤더 수정
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
Labels: BE, ✨ feat, 🔎 test

#258 캐릭터 이미지 저장방식 수정, 관련 api 수정
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
  src/main/java/com/exchangediary/group/service/GroupCreateService.java
  src/main/java/com/exchangediary/group/service/GroupJoinService.java
  src/main/java/com/exchangediary/group/service/GroupValidationService.java
  src/main/java/com/exchangediary/group/ui/dto/request/GroupCreateRequest.java
  src/main/java/com/exchangediary/group/ui/dto/request/GroupJoinRequest.java
  src/main/java/com/exchangediary/group/ui/dto/response/GroupMembersResponse.java
  src/main/java/com/exchangediary/group/ui/dto/response/GroupProfileResponse.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
  src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
  src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
  src/test/java/com/exchangediary/member/domain/MemberRepositoryUnitTest.java
Labels: BE, 🛠️ refactor

#259 캐릭터 이미지 css 분리 및 통신 시 키 값 수정
  src/main/resources/static/css/character.css
  src/main/resources/static/css/group/group-step3.css
  src/main/resources/static/images/character/blue.svg
  src/main/resources/static/images/character/gray-blue.svg
  src/main/resources/static/images/character/gray-green.svg
  src/main/resources/static/images/character/gray-navy.svg
  src/main/resources/static/images/character/gray-orange.svg
  src/main/resources/static/images/character/gray-purple.svg
  src/main/resources/static/images/character/gray-red.svg
  src/main/resources/static/images/character/gray-yellow.svg
  src/main/resources/static/images/character/green.svg
  src/main/resources/static/images/character/navy.svg
  src/main/resources/static/images/character/orange.svg
  src/main/resources/static/images/character/purple.svg
  src/main/resources/static/images/character/red.svg
  src/main/resources/static/images/character/yellow.svg
  src/main/resources/static/images/group/character/select-border.svg
  src/main/resources/static/js/group/group-common.js
  src/main/resources/static/js/group/group-step3.js
  src/main/resources/static/js/group/group-step4.js
  src/main/resources/templates/base.html
Labels: FE, 🛠️ refactor

#229 일기 작성 시 사진 첨부 기능 구현
  src/main/resources/static/css/diary/diary-common.css
  src/main/resources/static/css/diary/modal.css
  src/main/resources/static/images/diary/write-page/modal/camera_icon.svg
  src/main/resources/static/images/diary/write-page/modal/photo_icon.svg
  src/main/resources/static/images/diary/write-page/success_background.svg
  src/main/resources/static/images/diary/write-page/test.png
  src/main/resources/static/js/diary/write-page/modal.js
  src/main/resources/static/js/diary/write-page/photo.js
  src/main/resources/static/js/diary/write-page/write-diary.js
  src/main/resources/templates/diary/write-page.html
Labels: FE, ✨ feat

#232 일기 작성 페이지 및 그룹 생성/가입 단계에 에러 모달 추가
  src/main/resources/static/css/group/group-step4.css
  src/main/resources/static/js/diary/write-page/write-diary.js
  src/main/resources/static/js/group/group-step2.js
  src/main/resources/static/js/group/group-step4.js
  src/main/resources/templates/group-page.html
Labels: FE, ✨ feat

#260 에러 메시지 기획과 통일시키기
  src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  src/main/java/com/exchangediary/diary/ui/dto/request/DiaryRequest.java
  src/main/java/com/exchangediary/global/exception/ApiErrorResponse.java
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/group/service/GroupCodeService.java
  src/main/java/com/exchangediary/group/service/GroupCreateService.java
  src/main/java/com/exchangediary/group/ui/dto/request/GroupCodeRequest.java
  src/main/java/com/exchangediary/group/ui/dto/request/GroupNicknameRequest.java
Labels: BE, 🛠️ refactor

#262 그룹원 간 일기 작성 순서 개념 반영
  src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryWritableStatusResponse.java
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  src/main/java/com/exchangediary/global/exception/serviceexception/ForbiddenException.java
  src/main/java/com/exchangediary/group/domain/entity/Group.java
  src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
Labels: BE, ✨ feat, 🔎 test

#267 사진 업로드 취소 구현
  src/main/resources/static/css/diary/diary-common.css
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/static/images/diary/write-page/cancel-upload.svg
  src/main/resources/static/js/diary/write-page/photo.js
  src/main/resources/templates/diary/write-page.html
Labels: FE, ✨ feat

#269 그룹원 순서에 따른 정보 조회 API 구현
  src/main/java/com/exchangediary/group/domain/entity/Group.java
  src/main/java/com/exchangediary/group/service/GroupQueryService.java
  src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  src/main/java/com/exchangediary/group/ui/dto/response/GroupMembersResponse.java
  src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
  src/test/java/com/exchangediary/group/service/GroupQueryServiceTest.java
Labels: BE, ✨ feat, 🔎 test

#271 그룹 역할 필드 추가
  src/main/java/com/exchangediary/group/service/GroupCreateService.java
  src/main/java/com/exchangediary/group/service/GroupJoinService.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/main/java/com/exchangediary/member/domain/enums/GroupRole.java
  src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
  src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
  src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
  src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
Labels: BE, ✨ feat, 🔎 test

#274 프론트 리팩터링
  src/main/resources/static/css/character.css
  src/main/resources/static/css/group/group-step3.css
  src/main/resources/static/js/diary/view-diary/draw-diary.js
  src/main/resources/static/js/group/group-step3.js
  src/main/resources/static/js/group/group-step4.js
  src/main/resources/templates/diary/view-diary.html
Labels: FE, 🛠️ refactor

#265 일기 작성시, 이미지 크기와 형식 예외 처리
  src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
Labels: BE, ✨ feat, 🔎 test

#275 방장 넘기기 API 구현
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/group/service/GroupQueryService.java
  src/main/java/com/exchangediary/group/ui/ApiGroupLeaderController.java
  src/main/java/com/exchangediary/group/ui/dto/request/GroupLeaderHandOverRequest.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/test/java/com/exchangediary/group/api/GroupLeaderHandOverApiTest.java
Labels: BE, ✨ feat, 🔎 test

#278 일기 작성 상태 조회 api 수정 - 볼 수 있는 일기id 값 반환
  src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryWritableStatusResponse.java
  src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
Labels: BE, ✨ feat

#281 달력형 페이지 변경사항 반영
  src/main/java/com/exchangediary/group/service/GroupQueryService.java
  src/main/java/com/exchangediary/group/ui/GroupController.java
  src/main/java/com/exchangediary/group/ui/dto/response/GroupMonthlyResponse.java
  src/main/resources/static/css/group/monthly-page.css
  src/main/resources/static/images/group/monthly-page/background.svg
  src/main/resources/static/js/group/create-join/group-common.js
  src/main/resources/static/js/group/create-join/group-step1.js
  src/main/resources/static/js/group/create-join/group-step2.js
  src/main/resources/static/js/group/create-join/group-step3.js
  src/main/resources/static/js/group/create-join/group-step4.js
  src/main/resources/static/js/group/create-join/group-step5.js
  src/main/resources/static/js/group/monthly/calendar-arrow.js
  src/main/resources/static/js/group/monthly/draw-bottom.js
  src/main/resources/static/js/group/monthly/draw-calendar.js
  src/main/resources/static/js/monthly-page/draw-calendar.js
  src/main/resources/templates/group/group-create-join.html
  src/main/resources/templates/group/group-monthly.html
Labels: FE, ✨ feat

#285 일기 서비스 리팩터링
  src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  src/main/java/com/exchangediary/diary/domain/entity/UploadImage.java
  src/main/java/com/exchangediary/diary/service/DiaryCommandService.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/service/DiaryValidationService.java
  src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
  src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java
Labels: BE, 🛠️ refactor, 🔎 test

#288 테스트에서 발생하는 not null 제약조건 오류 해결
  src/main/java/com/exchangediary/group/domain/entity/Group.java
  src/main/java/com/exchangediary/group/service/GroupCreateService.java
  src/test/java/com/exchangediary/diary/api/DiaryCreateApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryFindIdApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
  src/test/java/com/exchangediary/diary/service/DiaryQueryServiceTest.java
  src/test/java/com/exchangediary/group/api/GroupCodeApiTest.java
  src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaderHandOverApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaderSkipOrderApiTest.java
  src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
  src/test/java/com/exchangediary/group/api/GroupNicknameApiTest.java
  src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
  src/test/java/com/exchangediary/group/service/GroupCodeServiceTest.java
  src/test/java/com/exchangediary/member/domain/MemberRepositoryUnitTest.java
Labels: BE, 🐞 bug, 🔎 test

#289 일기 작성 인가 인터셉터 구현
  src/main/java/com/exchangediary/diary/service/DiaryAuthorizationService.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/global/config/web/WebConfig.java
  src/main/java/com/exchangediary/global/config/web/interceptor/WriteDiaryAuthorizationInterceptor.java
  src/main/java/com/exchangediary/group/domain/GroupRepository.java
  src/main/java/com/exchangediary/group/service/GroupQueryService.java
  src/test/java/com/exchangediary/global/config/interceptor/WriteDiaryAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/group/domain/GroupRepositoryUnitTest.java
Labels: BE, ✨ feat, 🔎 test

#279 그룹 나가기 API 구현
  src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  src/main/java/com/exchangediary/group/domain/entity/Group.java
  src/main/java/com/exchangediary/group/service/GroupLeaveService.java
  src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/test/java/com/exchangediary/group/api/GroupLeaveApiTest.java
Labels: BE, ✨ feat, 🔎 test

#282 그룹원 정보 조회 API 수정
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/group/service/GroupMemberService.java
  src/main/java/com/exchangediary/group/service/GroupQueryService.java
  src/main/java/com/exchangediary/group/ui/dto/response/GroupMembersResponse.java
  src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
Labels: BE, ✨ feat, 🔎 test

#293 그룹 생성/가입 페이지 오류 관리
  src/main/resources/static/css/group/group-common.css
  src/main/resources/static/images/group/note.svg
  src/main/resources/static/js/common/base.js
  src/main/resources/static/js/common/notification-modal/modal.js
  src/main/resources/static/js/diary/write-page/write-diary.js
  src/main/resources/static/js/group/create-join/group-common.js
  src/main/resources/static/js/group/create-join/group-step1.js
  src/main/resources/static/js/group/create-join/group-step2.js
  src/main/resources/static/js/group/create-join/group-step3.js
  src/main/resources/static/js/group/create-join/group-step4.js
  src/main/resources/static/js/group/create-join/group-step5.js
  src/main/resources/templates/base.html
  src/main/resources/templates/group/group-create-join.html
Labels: FE, 🐞 bug

#298 방장 권한 넘기기 API 수정
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/group/service/GroupMemberService.java
  src/main/java/com/exchangediary/group/ui/dto/request/GroupLeaderHandOverRequest.java
  src/test/java/com/exchangediary/group/api/GroupLeaderHandOverApiTest.java
Labels: BE, ✨ feat, 🔎 test

#291 일기 조회 인가 구현
  src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  src/main/java/com/exchangediary/diary/service/DiaryAuthorizationService.java
  src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
  src/main/java/com/exchangediary/global/config/web/WebConfig.java
  src/main/java/com/exchangediary/global/config/web/interceptor/ViewDiaryAuthorizationInterceptor.java
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/group/service/GroupCreateService.java
  src/main/java/com/exchangediary/group/service/GroupJoinService.java
  src/main/java/com/exchangediary/group/service/GroupLeaveService.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/main/java/com/exchangediary/member/service/MemberRegistrationService.java
  src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
  src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java
  src/test/java/com/exchangediary/global/config/interceptor/ViewDiaryAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/WriteDiaryAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaderHandOverApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaderSkipOrderApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaveApiTest.java
  src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
  src/test/java/com/exchangediary/group/domain/GroupRepositoryUnitTest.java
Labels: BE, ✨ feat, 🔎 test

#286 그룹원 강퇴 API 구현
  src/main/java/com/exchangediary/group/domain/entity/Group.java
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/group/ui/ApiGroupLeaderController.java
  src/main/java/com/exchangediary/group/ui/dto/request/GroupKickOutRequest.java
  src/main/java/com/exchangediary/member/domain/MemberRepository.java
  src/test/java/com/exchangediary/group/api/GroupLeaderKickOutApiTest.java
Labels: BE, ✨ feat, 🔎 test

#299 인터셉터 리팩터링 및 테스트 작성
  src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  src/main/java/com/exchangediary/diary/service/DiaryAuthorizationService.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/service/DiaryValidationService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/global/config/web/WebConfig.java
  src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
  src/main/java/com/exchangediary/global/config/web/interceptor/WriteDiaryAuthorizationInterceptor.java
  src/main/java/com/exchangediary/group/domain/GroupRepository.java
  src/main/java/com/exchangediary/group/service/GroupMemberService.java
  src/main/java/com/exchangediary/group/service/GroupQueryService.java
  src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java
  src/test/java/com/exchangediary/global/config/interceptor/BelongToGroupInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/JwtAuthenticationInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/LoginInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/WriteDiaryAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/group/domain/GroupRepositoryUnitTest.java
  src/test/java/com/exchangediary/member/api/LoginApiTest.java
Labels: BE, 🛠️ refactor, 🔎 test

#302 그룹 상세 페이지 구현
  src/main/java/com/exchangediary/group/ui/GroupController.java
  src/main/java/com/exchangediary/group/ui/dto/response/GroupMonthlyResponse.java
  src/main/resources/static/css/character.css
  src/main/resources/static/css/confirm-modal.css
  src/main/resources/static/css/group/group-menu.css
  src/main/resources/static/css/group/group-step3.css
  src/main/resources/static/css/group/monthly-page.css
  src/main/resources/static/css/notification-modal.css
  src/main/resources/static/images/common/confirm-modal/background.svg
  src/main/resources/static/images/common/confirm-modal/big-background.svg
  src/main/resources/static/images/common/confirm-modal/warning.svg
  src/main/resources/static/images/group/menu/background-icons.svg
  src/main/resources/static/images/group/menu/crown.svg
  src/main/resources/static/images/group/menu/exit.svg
  src/main/resources/static/images/group/menu/members-circle.svg
  src/main/resources/static/images/group/menu/partition-line.svg
  src/main/resources/static/images/group/menu/skip.svg
  src/main/resources/static/images/group/menu/white-crown.svg
  src/main/resources/static/images/monthly-page/menu-icon.svg
  src/main/resources/static/js/common/modal/confirm-modal.js
  src/main/resources/static/js/common/modal/notification-modal.js
  src/main/resources/static/js/group/group-menu.js
  src/main/resources/static/js/group/leader.js
  src/main/resources/static/js/group/monthly/draw-bottom.js
  src/main/resources/templates/base.html
  src/main/resources/templates/common/confirm-modal.html
  src/main/resources/templates/common/notification-modal.html
  src/main/resources/templates/group/group-menu.html
  src/main/resources/templates/group/group-monthly.html
Labels: FE, ✨ feat

#300 방장 인가 인터셉터 구현
  src/main/java/com/exchangediary/global/config/web/WebConfig.java
  src/main/java/com/exchangediary/global/config/web/interceptor/GroupLeaderAuthorizationInterceptor.java
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/member/domain/MemberRepository.java
  src/test/java/com/exchangediary/global/config/interceptor/GroupLeaderAuthorizationInterceptorTest.java
Labels: BE, ✨ feat, 🔎 test

#305 달력형 조회 API 수정
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDayResponse.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
  src/main/java/com/exchangediary/member/domain/MemberRepository.java
  src/main/java/com/exchangediary/member/service/MemberQueryService.java
  src/main/resources/static/js/group/monthly/draw-calendar.js
  src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
  src/test/java/com/exchangediary/global/config/interceptor/GroupLeaderAuthorizationInterceptorTest.java
Labels: BE, ✨ feat, 🔎 test

#301 일대일 연관관계 단방향으로 수정
  src/main/java/com/exchangediary/diary/domain/UploadImageRepository.java
  src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryResponse.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/main/java/com/exchangediary/member/service/MemberRegistrationService.java
  src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java
  src/test/java/com/exchangediary/diary/service/DiaryQueryServiceTest.java
  src/test/java/com/exchangediary/member/service/MemberRegistrationServiceTest.java
Labels: BE, 🤹 enhance

#304 그룹원 정보 조회 API 수정
  src/main/java/com/exchangediary/group/service/GroupMemberService.java
  src/main/java/com/exchangediary/group/service/GroupQueryService.java
  src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
Labels: BE, ✨ feat

#307 일기 건너뛰기 API 오류 해결
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/group/service/GroupMemberService.java
  src/test/java/com/exchangediary/group/api/GroupLeaderSkipOrderApiTest.java
Labels: BE, 🐞 bug

#308 월별형 페이지 일기 조회 인가 적용 및 화살표 정렬 문제 해결
  src/main/resources/static/css/character.css
  src/main/resources/static/css/group/group-common.css
  src/main/resources/static/css/group/group-step1.css
  src/main/resources/static/css/group/monthly-page.css
  src/main/resources/static/images/group/create-join-page/background.svg
  src/main/resources/static/images/group/create-join-page/group_create.svg
  src/main/resources/static/images/group/create-join-page/group_create_white.svg
  src/main/resources/static/images/group/create-join-page/group_join.svg
  src/main/resources/static/images/group/create-join-page/group_join_white.svg
  src/main/resources/static/images/group/create-join-page/heart.svg
  src/main/resources/static/images/group/create-join-page/logo.svg
  src/main/resources/static/images/group/create-join-page/note.svg
  src/main/resources/static/images/group/create-join-page/step1.svg
  src/main/resources/static/images/group/create-join-page/step2.svg
  src/main/resources/static/images/group/create-join-page/step3.svg
  src/main/resources/static/images/group/create-join-page/step4.svg
  src/main/resources/static/images/group/monthly-page/background.png
  src/main/resources/static/images/group/monthly-page/background.svg
  src/main/resources/static/js/group/create-join/group-step5.js
  src/main/resources/static/js/group/monthly/draw-calendar.js
  src/main/resources/templates/group/group-create-join.html
  src/main/resources/templates/group/group-monthly.html
Labels: FE, 🐞 bug, ✨ feat

#315 서버 배포를 하며 발생한 자잘한 프론트 버그
  src/main/resources/static/css/base.css
  src/main/resources/static/css/confirm-modal.css
  src/main/resources/static/css/diary/diary-common.css
  src/main/resources/static/css/diary/modal.css
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/static/css/group/group-common.css
  src/main/resources/static/css/group/group-menu.css
  src/main/resources/static/css/group/group-step1.css
  src/main/resources/static/css/group/group-step2.css
  src/main/resources/static/css/group/group-step3.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/notification-modal.css
  src/main/resources/static/js/diary/write-page/write-diary.js
  src/main/resources/static/js/group/group-menu.js
  src/main/resources/templates/base.html
Labels: FE, 🐞 bug, ✨ feat

#317 일기 작성 권한 없는 경우 오늘 날짜 클릭 비활성화
  src/main/resources/static/js/group/monthly/change-month.js
  src/main/resources/static/js/group/monthly/draw-bottom.js
  src/main/resources/static/js/group/monthly/draw-monthly.js
  src/main/resources/templates/group/group-monthly.html
Labels: FE, 🐞 bug

#318 일기 조회 페이지 닉네임 추가
  src/main/java/com/exchangediary/diary/ui/DiaryController.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryResponse.java
  src/main/resources/static/css/diary/diary-common.css
  src/main/resources/static/css/diary/modal.css
  src/main/resources/static/css/diary/view-page.css
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/static/images/diary/view-page/background.svg
  src/main/resources/static/js/diary/view-diary/draw-diary.js
  src/main/resources/static/js/diary/view-diary/view-diary.js
  src/main/resources/static/js/diary/write-page/modal.js
  src/main/resources/static/js/diary/write-page/photo.js
  src/main/resources/templates/diary/view-diary.html
  src/main/resources/templates/diary/view-page.html
  src/main/resources/templates/diary/write-page.html
Labels: FE, ✨ feat

#313 시작페이지 이미지 변경
  src/main/resources/static/images/start-page/background.png
  src/main/resources/static/images/start-page/background.svg
  src/main/resources/templates/start.html
Labels: FE, ✨ feat

#311 그룹 나가기 api 수정
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/group/service/GroupLeaveService.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/test/java/com/exchangediary/group/api/GroupLeaderKickOutApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaveApiTest.java
Labels: BE, ✨ feat, 🔎 test

#322 오늘의 기분 이미지 화질 개선
  src/main/resources/static/images/diary/write-page/emoji/blind.png
  src/main/resources/static/images/diary/write-page/emoji/blind.svg
  src/main/resources/static/images/diary/write-page/emoji/confident.png
  src/main/resources/static/images/diary/write-page/emoji/confident.svg
  src/main/resources/static/images/diary/write-page/emoji/confused.png
  src/main/resources/static/images/diary/write-page/emoji/confused.svg
  src/main/resources/static/images/diary/write-page/emoji/eyebags.png
  src/main/resources/static/images/diary/write-page/emoji/eyebags.svg
  src/main/resources/static/images/diary/write-page/emoji/fine.png
  src/main/resources/static/images/diary/write-page/emoji/fine.svg
  src/main/resources/static/images/diary/write-page/emoji/happy.png
  src/main/resources/static/images/diary/write-page/emoji/happy.svg
  src/main/resources/static/images/diary/write-page/emoji/indifferent.png
  src/main/resources/static/images/diary/write-page/emoji/indifferent.svg
  src/main/resources/static/images/diary/write-page/emoji/mad.png
  src/main/resources/static/images/diary/write-page/emoji/mad.svg
  src/main/resources/static/images/diary/write-page/emoji/merong.png
  src/main/resources/static/images/diary/write-page/emoji/merong.svg
  src/main/resources/static/images/diary/write-page/emoji/sad.png
  src/main/resources/static/images/diary/write-page/emoji/sad.svg
  src/main/resources/static/images/diary/write-page/emoji/shy.png
  src/main/resources/static/images/diary/write-page/emoji/shy.svg
  src/main/resources/static/images/diary/write-page/emoji/smile.png
  src/main/resources/static/images/diary/write-page/emoji/smile.svg
  src/main/resources/static/images/diary/write-page/emoji/sulk.png
  src/main/resources/static/images/diary/write-page/emoji/sulk.svg
  src/main/resources/static/images/diary/write-page/emoji/surprised.png
  src/main/resources/static/images/diary/write-page/emoji/surprised.svg
  src/main/resources/static/images/diary/write-page/emoji/tear.png
  src/main/resources/static/images/diary/write-page/emoji/tear.svg
  src/main/resources/static/images/diary/write-page/emoji/tired.png
  src/main/resources/static/images/diary/write-page/emoji/tired.svg
  src/main/resources/static/images/diary/write-page/emoji/upset.png
  src/main/resources/static/images/diary/write-page/emoji/upset.svg
  src/main/resources/static/images/diary/write-page/emoji/wink.png
  src/main/resources/static/images/diary/write-page/emoji/wink.svg
  src/main/resources/templates/diary/write-page.html
Labels: FE, 🛠️ refactor

#320 그룹 가입 시 일기 조회 가능 범위 변경
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/test/java/com/exchangediary/group/domain/GroupRepositoryUnitTest.java
Labels: BE, ✨ feat

#344 방장은 탈퇴 및 위임을 할 수 없음
  src/main/resources/static/js/common/modal/confirm-modal.js
  src/main/resources/static/js/group/group-menu.js
  src/main/resources/static/js/group/leader.js
Labels: FE, 🐞 bug, 🛠️ refactor

#346 백엔드 에러 로깅 추가
  .gitignore
  build.gradle
  src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  src/main/resources/console-appender.xml
  src/main/resources/file-error-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/jdbc-appender.xml
  src/main/resources/jdbc-loggers.xml
  src/main/resources/log4jdbc.log4j2.properties
  src/main/resources/logback-spring.xml
Labels: BE, ✨ feat

#348 그룹 탈퇴 시, 조회 가능한 마지막 일기 날짜 업데이트 오류 해결
  src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/group/service/GroupLeaveService.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
  src/test/java/com/exchangediary/global/config/interceptor/ViewDiaryAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/group/api/GroupCreateApiTest.java
  src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaveApiTest.java
Labels: BE, 🐞 bug, 🔎 test

#354 달력형 페이지에서 디비 접근 횟수 줄이기
  src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  src/main/java/com/exchangediary/diary/domain/dto/DiaryDay.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDayResponse.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
  src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
  src/main/java/com/exchangediary/group/ui/GroupController.java
  src/main/java/com/exchangediary/member/service/MemberQueryService.java
  src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
Labels: BE, 🤹 enhance

#355 월별형 API 수정
  src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  src/main/java/com/exchangediary/diary/domain/dto/DiaryDay.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryDayResponse.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryMonthlyResponse.java
  src/main/java/com/exchangediary/member/service/MemberQueryService.java
  src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
Labels: BE, 🛠️ refactor
