Repository Buddies2024/spring, pull requests merged in 2024-11, with the labels that each got.

#356 일기 작성/조회 인가 인터셉터 제거 및 그룹 인가 인터셉터 리팩터링
  src/main/java/com/exchangediary/diary/service/DiaryAuthorizationService.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/service/DiaryValidationService.java
  src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
  src/main/java/com/exchangediary/diary/ui/DiaryController.java
  src/main/java/com/exchangediary/global/config/web/WebConfig.java
  src/main/java/com/exchangediary/global/config/web/interceptor/BelongToGroupInterceptor.java
  src/main/java/com/exchangediary/global/config/web/interceptor/GroupAuthorizationInterceptor.java
  src/main/java/com/exchangediary/global/config/web/interceptor/GroupMemberAuthorizationInterceptor.java
  src/main/java/com/exchangediary/global/config/web/interceptor/ViewDiaryAuthorizationInterceptor.java
  src/main/java/com/exchangediary/global/config/web/interceptor/WriteDiaryAuthorizationInterceptor.java
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/member/service/MemberQueryService.java
  src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
  src/test/java/com/exchangediary/diary/service/DiaryQueryServiceTest.java
  src/test/java/com/exchangediary/global/config/interceptor/BelongToGroupInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/GroupAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/ViewDiaryAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/WriteDiaryAuthorizationInterceptorTest.java
Labels: BE, 🛠️ refactor, 🔎 test

#358 일기 작성, 조회 API 수정
  .gitignore
  src/main/java/com/exchangediary/diary/domain/DiaryContentRepository.java
  src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  src/main/java/com/exchangediary/diary/domain/UploadImageRepository.java
  src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  src/main/java/com/exchangediary/diary/domain/entity/DiaryContent.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/diary/ui/DiaryController.java
  src/main/java/com/exchangediary/diary/ui/dto/request/DiaryContentRequest.java
  src/main/java/com/exchangediary/diary/ui/dto/request/DiaryRequest.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryContentResponse.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryResponse.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryTopResponse.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/main/java/com/exchangediary/member/service/MemberRegistrationService.java
  src/main/resources/schema.sql
  src/test/java/com/exchangediary/diary/api/DiaryFindIdApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryViewApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
  src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java
  src/test/java/com/exchangediary/diary/service/DiaryQueryServiceTest.java
  src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
  src/test/java/com/exchangediary/group/domain/GroupRepositoryUnitTest.java
  src/test/java/com/exchangediary/member/service/ExpiredJwtTest.java
  src/test/java/com/exchangediary/member/service/RefreshTokenVerifyTest.java
  src/test/resources/truncate.sql
Labels: BE, ✨ feat, 🔎 test

#363 fcm 환경 세팅 및 새로운 그룹원 가입 알림 구현
  .gitignore
  build.gradle
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/global/exception/serviceexception/MessagingFailureException.java
  src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  src/main/java/com/exchangediary/member/service/KakaoService.java
  src/main/java/com/exchangediary/notification/config/FCMControllerAdvice.java
  src/main/java/com/exchangediary/notification/config/FCMInitializer.java
  src/main/java/com/exchangediary/notification/domain/NotificationRepository.java
  src/main/java/com/exchangediary/notification/domain/entity/Notification.java
  src/main/java/com/exchangediary/notification/service/MessageSendService.java
  src/main/java/com/exchangediary/notification/service/NotificationService.java
  src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
  src/main/java/com/exchangediary/notification/ui/ApiNotificationController.java
  src/main/java/com/exchangediary/notification/ui/dto/request/NotificationTokenRequest.java
  src/main/resources/schema.sql
  src/main/resources/static/firebase-messaging-sw.js
  src/main/resources/static/js/fcm/setup-fcm.js
  src/main/resources/templates/base.html
  src/test/java/com/exchangediary/ApiBaseTest.java
  src/test/java/com/exchangediary/notification/api/NotificationApiTest.java
  src/test/resources/truncate.sql
Labels: BE, FE, ✨ feat, 🔎 test

#365 403, 404 에러 페이지 구현
  src/main/java/com/exchangediary/global/config/web/interceptor/GroupAuthorizationInterceptor.java
  src/main/java/com/exchangediary/global/exception/ApiErrorResponse.java
  src/main/java/com/exchangediary/global/exception/ErrorCode.java
  src/main/java/com/exchangediary/global/exception/GlobalExceptionHandler.java
  src/main/java/com/exchangediary/global/exception/RequestValidationExceptionHandler.java
  src/main/java/com/exchangediary/global/exception/ServiceExceptionHandler.java
  src/main/resources/static/css/error.css
  src/main/resources/static/images/error/background-403.png
  src/main/resources/static/images/error/background-404.png
  src/main/resources/static/images/error/background-common.png
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/common.html
  src/test/java/com/exchangediary/global/config/interceptor/GroupAuthorizationInterceptorTest.java
Labels: BE, FE, ✨ feat

#374 일기 알림 구현
  src/main/java/com/exchangediary/ExchangediaryApplication.java
  src/main/java/com/exchangediary/diary/service/DiaryAuthorizationService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  src/main/java/com/exchangediary/group/ui/ApiGroupLeaderController.java
  src/main/java/com/exchangediary/notification/config/NotificationScheduler.java
  src/main/java/com/exchangediary/notification/domain/NotificationRepository.java
  src/main/java/com/exchangediary/notification/service/MessageSendService.java
  src/main/java/com/exchangediary/notification/service/NotificationService.java
  src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
  src/test/java/com/exchangediary/notification/domain/NotificationRepositoryUnitTest.java
Labels: BE, ✨ feat, 🔎 test

#377 무한로딩 버그 해결
  src/main/java/com/exchangediary/global/config/web/WebConfig.java
  src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
  src/main/java/com/exchangediary/global/config/web/interceptor/LoginInterceptor.java
  src/test/java/com/exchangediary/global/config/interceptor/JwtAuthenticationInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/LoginInterceptorTest.java
Labels: BE, 🐞 bug

#382 오늘의 기분 이모티콘 이미지 중복 해결
  src/main/resources/static/images/diary/write-page/emoji/sulk.png
Labels: FE, 🐞 bug

#380 그룹 코드 수정
  src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  src/main/java/com/exchangediary/diary/service/DiaryAuthorizationService.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/diary/ui/DiaryController.java
  src/main/java/com/exchangediary/global/config/web/interceptor/GroupAuthorizationInterceptor.java
  src/main/java/com/exchangediary/group/domain/GroupRepository.java
  src/main/java/com/exchangediary/group/domain/RandomIdGenerator.java
  src/main/java/com/exchangediary/group/domain/entity/Group.java
  src/main/java/com/exchangediary/group/service/GroupCodeService.java
  src/main/java/com/exchangediary/group/service/GroupCreateService.java
  src/main/java/com/exchangediary/group/service/GroupJoinService.java
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/group/service/GroupLeaveService.java
  src/main/java/com/exchangediary/group/service/GroupQueryService.java
  src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  src/main/java/com/exchangediary/group/ui/ApiGroupLeaderController.java
  src/main/java/com/exchangediary/group/ui/GroupController.java
  src/main/java/com/exchangediary/group/ui/dto/response/GroupCreateResponse.java
  src/main/java/com/exchangediary/group/ui/dto/response/GroupIdResponse.java
  src/main/java/com/exchangediary/group/ui/dto/response/GroupMonthlyResponse.java
  src/main/java/com/exchangediary/member/domain/dto/GroupId.java
  src/main/java/com/exchangediary/member/service/MemberQueryService.java
  src/main/java/com/exchangediary/notification/domain/NotificationRepository.java
  src/main/java/com/exchangediary/notification/service/NotificationService.java
  src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
  src/main/resources/static/js/group/create-join/group-step5.js
  src/main/resources/templates/diary/write-page.html
  src/main/resources/templates/group/group-menu.html
  src/main/resources/templates/group/group-monthly.html
  src/test/java/com/exchangediary/comment/api/CommentCreateApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryViewApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
  src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java
  src/test/java/com/exchangediary/diary/service/DiaryQueryServiceTest.java
  src/test/java/com/exchangediary/global/config/interceptor/GroupAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/GroupLeaderAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/group/api/GroupCodeApiTest.java
  src/test/java/com/exchangediary/group/api/GroupJoinApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaderHandOverApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaderKickOutApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaderSkipOrderApiTest.java
  src/test/java/com/exchangediary/group/api/GroupLeaveApiTest.java
  src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
  src/test/java/com/exchangediary/group/api/GroupNicknameApiTest.java
  src/test/java/com/exchangediary/group/api/GroupProfileApiTest.java
  src/test/java/com/exchangediary/group/domain/GroupRepositoryUnitTest.java
  src/test/java/com/exchangediary/group/service/GroupCodeServiceTest.java
  src/test/java/com/exchangediary/member/domain/MemberRepositoryUnitTest.java
  src/test/java/com/exchangediary/notification/domain/NotificationRepositoryUnitTest.java
Labels: BE, 🛠️ refactor, 🔎 test

#388 사진 저장 경로 수정
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/service/DiaryValidationService.java
  src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
  src/main/java/com/exchangediary/diary/service/ImageService.java
  src/main/java/com/exchangediary/global/config/web/WebConfig.java
Labels: BE, 🐞 bug

#386 일기 조회/작성 페이지 수정
  .gitignore
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/diary/ui/DiaryController.java
  src/main/java/com/exchangediary/global/config/web/WebConfig.java
  src/main/java/com/exchangediary/global/config/web/interceptor/GroupAuthorizationInterceptor.java
  src/main/java/com/exchangediary/global/config/web/interceptor/JwtAuthenticationInterceptor.java
  src/main/java/com/exchangediary/group/ui/GroupController.java
  src/main/java/com/exchangediary/member/ui/KakaoLoginController.java
  src/main/resources/static/css/base.css
  src/main/resources/static/css/confirm-modal.css
  src/main/resources/static/css/diary/diary-common.css
  src/main/resources/static/css/diary/modal.css
  src/main/resources/static/css/diary/view-page.css
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/static/css/group/group-common.css
  src/main/resources/static/css/group/monthly-page.css
  src/main/resources/static/css/notification-modal.css
  src/main/resources/static/css/start.css
  src/main/resources/static/images/diary/view-page/default-image.png
  src/main/resources/static/js/diary/view-diary/slide-diary.js
  src/main/resources/static/js/diary/view-diary/view-diary.js
  src/main/resources/static/js/diary/write-page/check-textarea.js
  src/main/resources/static/js/diary/write-page/modal.js
  src/main/resources/static/js/diary/write-page/sync-textarea.js
  src/main/resources/static/js/diary/write-page/write-diary.js
  src/main/resources/static/js/group/create-join/group-step5.js
  src/main/resources/static/js/group/group-menu.js
  src/main/resources/static/js/group/monthly/draw-bottom.js
  src/main/resources/static/js/group/monthly/draw-monthly.js
  src/main/resources/templates/diary/view-page.html
  src/main/resources/templates/diary/write-page.html
  src/main/resources/templates/group/group-create-join.html
  src/main/resources/templates/group/group-monthly.html
  src/main/resources/templates/login.html
  src/main/resources/templates/start.html
  src/test/java/com/exchangediary/global/config/interceptor/GroupAuthorizationInterceptorTest.java
  src/test/java/com/exchangediary/global/config/interceptor/JwtAuthenticationInterceptorTest.java
  src/test/resources/images/test.jpg
Labels: FE, ✨ feat

#392 스프린트3 배포하며 받은 피드백 반영
  src/main/resources/static/css/confirm-modal.css
  src/main/resources/static/css/diary/diary-common.css
  src/main/resources/static/css/diary/modal.css
  src/main/resources/static/css/diary/view-page.css
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/static/css/error.css
  src/main/resources/static/css/fonts.css
  src/main/resources/static/css/group/group-common.css
  src/main/resources/static/css/group/group-menu.css
  src/main/resources/static/css/group/group-step1.css
  src/main/resources/static/css/group/group-step2.css
  src/main/resources/static/css/group/group-step5.css
  src/main/resources/static/css/group/monthly-page.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/notification-modal.css
  src/main/resources/static/js/diary/write-page/write-diary.js
  src/main/resources/static/js/group/create-join/group-step5.js
  src/main/resources/static/js/group/group-menu.js
  src/main/resources/static/js/group/leader.js
  src/main/resources/templates/diary/write-page.html
Labels: FE, ✨ feat

#397 일기 작성 페이지 엔터 및 백스페이스 기능 개선
  src/main/resources/static/js/diary/write-page/check-textarea.js
Labels: FE, 🤹 enhance, ✨ feat

#395 사용자 - 알림 연관관계 변경 및 fcm 토큰 신선도 관리
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  src/main/java/com/exchangediary/group/ui/ApiGroupLeaderController.java
  src/main/java/com/exchangediary/notification/component/FCMControllerAdvice.java
  src/main/java/com/exchangediary/notification/component/FCMInitializer.java
  src/main/java/com/exchangediary/notification/component/NotificationScheduler.java
  src/main/java/com/exchangediary/notification/domain/NotificationRepository.java
  src/main/java/com/exchangediary/notification/domain/entity/Notification.java
  src/main/java/com/exchangediary/notification/service/MessageSendService.java
  src/main/java/com/exchangediary/notification/service/NotificationService.java
  src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
  src/main/resources/db/migration/V2.8__delete_unique_index_on_notification_member_id.sql
  src/test/java/com/exchangediary/notification/api/NotificationApiTest.java
  src/test/java/com/exchangediary/notification/domain/NotificationRepositoryUnitTest.java
Labels: BE, ✨ feat, 🔎 test

#399 그룹 - 사용자 외래키 제약조건 수정
  src/main/resources/db/migration/V2.9__alter__member_group_foreign_key.sql
Labels: BE, 🐞 bug

#402 일기 작성 테스트 logFilter 오류 해결
  src/main/java/com/exchangediary/global/config/log/RequestLoggingConfig.java
  src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
Labels: BE, 🐞 bug

#404 스키마 구조 쿼리 오류 해결
  src/main/resources/db/migration/V2.2__drop_upload_image.sql
  src/main/resources/db/migration/V2.3__create_diary_content.sql
Labels: BE, 🐞 bug

#405 첫번째 페이지 생성 오류 해결
  src/main/resources/db/migration/V2.3__create_diary_content.sql
Labels: BE, 🐞 bug

#416 diary content 테이블 content 열 길이 늘리기
  src/main/resources/db/migration/V2.10__alter_diary_content_content.sql
Labels: BE, 🐞 bug

#418 설정파일 git에서 관리하도록 변경
  .gitignore
  src/main/java/com/exchangediary/ExchangediaryApplication.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: BE, ⚙️ setting

#425 일기 삭제 시 이미지 파일 삭제 및 fcm 토큰 유니크 제약조건 추가
  src/main/java/com/exchangediary/diary/domain/DiaryRepository.java
  src/main/java/com/exchangediary/diary/service/DiaryDeleteService.java
  src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
  src/main/java/com/exchangediary/diary/service/ImageService.java
  src/main/java/com/exchangediary/group/service/GroupLeaveService.java
  src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
  src/main/resources/db/migration/V3.2__add_unique_index_on_token.sql
Labels: BE, 🐞 bug, ✨ feat

#428 오늘의 기분 컬럼명 수정 및 속성값 변경
  src/main/java/com/exchangediary/diary/domain/entity/Diary.java
  src/main/java/com/exchangediary/diary/service/DiaryQueryService.java
  src/main/java/com/exchangediary/diary/ui/dto/request/DiaryRequest.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryTopResponse.java
  src/main/resources/db/migration/V3.2__add_unique_index_on_token.sql
  src/main/resources/db/migration/V3.4__alter_mood_column_name.sql
  src/main/resources/static/js/diary/write-page/write-diary.js
  src/main/resources/templates/diary/view-page.html
  src/test/java/com/exchangediary/comment/api/CommentCreateApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryViewApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryViewMonthlyTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWritableStatusApiTest.java
  src/test/java/com/exchangediary/diary/api/DiaryWriteApiTest.java
  src/test/java/com/exchangediary/diary/domain/DiaryRepositoryUnitTest.java
  src/test/java/com/exchangediary/diary/service/DiaryQueryServiceTest.java
  src/test/java/com/exchangediary/group/api/GroupMembersOrderApiTest.java
  src/test/java/com/exchangediary/notification/domain/NotificationRepositoryUnitTest.java
  src/test/java/com/exchangediary/reply/api/ReplyCreateApiTest.java
Labels: BE, FE, 🤹 enhance

#430 GA 스크립트 수정
  src/main/resources/templates/base.html
Labels: FE, ⚙️ setting

#431 일기 조회 api 수정 - 댓글 기능 추가
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryCommentResponse.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryContentResponse.java
  src/main/java/com/exchangediary/diary/ui/dto/response/DiaryResponse.java
  src/test/java/com/exchangediary/diary/api/DiaryViewApiTest.java
Labels: BE, ✨ feat

#432 댓글창 생성 유효성 검증 API
  src/main/java/com/exchangediary/comment/domain/CommentRepository.java
  src/main/java/com/exchangediary/comment/service/CommentAuthorizationService.java
  src/main/java/com/exchangediary/comment/service/CommentQueryService.java
  src/main/java/com/exchangediary/comment/ui/ApiCommentController.java
  src/main/java/com/exchangediary/comment/ui/dto/response/CommentCreationVerifyResponse.java
  src/test/java/com/exchangediary/comment/api/CommentCreationVerifyApiTest.java
Labels: BE, ✨ feat, 🔎 test

#433 댓글 한 개 조회 API
  src/main/java/com/exchangediary/comment/service/CommentQueryService.java
  src/main/java/com/exchangediary/comment/ui/ApiCommentController.java
  src/main/java/com/exchangediary/comment/ui/dto/response/CommentResponse.java
  src/main/java/com/exchangediary/comment/ui/dto/response/ReplyResponse.java
  src/test/java/com/exchangediary/comment/api/CommentViewApiTest.java
  src/test/java/com/exchangediary/comment/api/ReplyCreateApiTest.java
Labels: BE, ✨ feat, 🔎 test
