Repository Buddies2024/spring, pull requests merged in 2025-04, with the labels that each got.

#489 도커 컴포즈 추가
  .gitignore
  build.gradle
  docker-compose.yml
  settings.gradle
  src/main/java/com/exchangediary/member/service/CookieService.java
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
  src/test/resources/application.properties
Labels: ⚙️ setting

#492 알림 활성화 속성 추가 및 API 구현
  src/main/java/com/exchangediary/diary/service/DiaryWriteService.java
  src/main/java/com/exchangediary/diary/ui/ApiDiaryController.java
  src/main/java/com/exchangediary/diary/ui/dto/notification/DiaryWriteNotification.java
  src/main/java/com/exchangediary/group/service/GroupCreateJoinService.java
  src/main/java/com/exchangediary/group/service/GroupLeaderService.java
  src/main/java/com/exchangediary/group/service/GroupLeaveService.java
  src/main/java/com/exchangediary/group/ui/ApiGroupController.java
  src/main/java/com/exchangediary/group/ui/ApiGroupLeaderController.java
  src/main/java/com/exchangediary/group/ui/dto/notification/GroupJoinNotification.java
  src/main/java/com/exchangediary/group/ui/dto/notification/GroupLeaderHandOverNotification.java
  src/main/java/com/exchangediary/group/ui/dto/notification/GroupLeaderKickOutNotification.java
  src/main/java/com/exchangediary/group/ui/dto/notification/GroupLeaderSkipDiaryNotification.java
  src/main/java/com/exchangediary/group/ui/dto/notification/GroupLeaveNotification.java
  src/main/java/com/exchangediary/member/domain/MemberRepository.java
  src/main/java/com/exchangediary/member/domain/entity/Member.java
  src/main/java/com/exchangediary/member/service/MemberQueryService.java
  src/main/java/com/exchangediary/member/service/MemberUpdateService.java
  src/main/java/com/exchangediary/member/ui/ApiMemberController.java
  src/main/java/com/exchangediary/member/ui/dto/response/MemberNotificationResponse.java
  src/main/java/com/exchangediary/notification/domain/NotificationRepository.java
  src/main/java/com/exchangediary/notification/service/NotificationTokenService.java
  src/main/resources/db/migration/V4.3__add_notifcation_on_column.sql
  src/test/java/com/exchangediary/member/api/OnNotificationApiTest.java
  src/test/java/com/exchangediary/notification/api/NotificationApiTest.java
  src/test/java/com/exchangediary/notification/domain/NotificationRepositoryUnitTest.java
Labels: BE, ✨ feat, 🔎 test

#493 1.2a 버전 프론트 관련 문제 수정
  src/main/resources/static/css/base.css
  src/main/resources/static/css/character.css
  src/main/resources/static/css/diary/comment.css
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/static/css/group/group-common.css
  src/main/resources/static/css/group/group-menu.css
  src/main/resources/static/css/group/monthly-page.css
  src/main/resources/static/css/notification-modal.css
  src/main/resources/static/css/start.css
  src/main/resources/static/images/group/menu/leave.svg
  src/main/resources/static/images/group/menu/notification-mute.svg
  src/main/resources/static/images/group/menu/notification.svg
  src/main/resources/static/images/monthly-page/left-arrow.svg
  src/main/resources/static/images/monthly-page/right-arrow.svg
  src/main/resources/static/images/start-page/background.png
  src/main/resources/static/images/start-page/background.svg
  src/main/resources/static/images/start-page/line.gif
  src/main/resources/static/images/start-page/logo.png
  src/main/resources/static/js/common/base.js
  src/main/resources/static/js/common/modal/confirm-modal.js
  src/main/resources/static/js/diary/view-diary/comment.js
  src/main/resources/static/js/diary/view-diary/view-diary.js
  src/main/resources/static/js/diary/write-page/check-textarea-android.js
  src/main/resources/static/js/diary/write-page/check-textarea-ios.js
  src/main/resources/static/js/diary/write-page/check-textarea.js
  src/main/resources/static/js/diary/write-page/modal.js
  src/main/resources/static/js/diary/write-page/photo.js
  src/main/resources/static/js/diary/write-page/write-diary.js
  src/main/resources/static/js/fcm/setup-fcm.js
  src/main/resources/static/js/group/create-join/group-common.js
  src/main/resources/static/js/group/create-join/group-step3.js
  src/main/resources/static/js/group/group-menu.js
  src/main/resources/static/js/group/leader.js
  src/main/resources/static/js/group/monthly/change-month.js
  src/main/resources/static/js/group/monthly/draw-bottom.js
  src/main/resources/static/js/group/monthly/draw-monthly.js
  src/main/resources/static/js/start-page/start.js
  src/main/resources/static/manifest.json
  src/main/resources/templates/base.html
  src/main/resources/templates/diary/view-page.html
  src/main/resources/templates/diary/write-page.html
  src/main/resources/templates/group/group-menu.html
  src/main/resources/templates/group/group-monthly.html
  src/main/resources/templates/start.html
Labels: FE, 🐞 bug, 🛠️ refactor

#496 v1.2 배포 후 발견된 버그 수정
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/static/css/group/group-menu.css
  src/main/resources/static/js/common/base.js
  src/main/resources/static/js/diary/write-page/check-textarea-android.js
  src/main/resources/static/js/diary/write-page/check-textarea-ios.js
  src/main/resources/static/js/diary/write-page/check-textarea.js
  src/main/resources/static/js/group/group-menu.js
  src/main/resources/static/js/group/monthly/draw-monthly.js
  src/main/resources/templates/group/group-monthly.html
Labels: FE, 🐞 bug

#497 Hotfix/v1.2.1
  src/main/resources/static/css/diary/write-page.css
  src/main/resources/static/css/group/group-menu.css
  src/main/resources/static/js/common/base.js
  src/main/resources/static/js/diary/write-page/check-textarea-android.js
  src/main/resources/static/js/diary/write-page/check-textarea-ios.js
  src/main/resources/static/js/diary/write-page/check-textarea.js
  src/main/resources/static/js/group/group-menu.js
  src/main/resources/static/js/group/monthly/draw-monthly.js
  src/main/resources/templates/group/group-monthly.html
Labels: BE, FE, 🐞 bug, DESIGN

#503 메타 설명 추가 및 사이트 이름 변경
  src/main/resources/templates/base.html
  src/main/resources/templates/diary/view-page.html
  src/main/resources/templates/diary/write-page.html
  src/main/resources/templates/error/403.html
  src/main/resources/templates/error/404.html
  src/main/resources/templates/error/common.html
  src/main/resources/templates/group/group-create-join.html
  src/main/resources/templates/group/group-monthly.html
  src/main/resources/templates/login.html
  src/main/resources/templates/start.html
Labels: FE, ✨ feat, 🛠️ refactor
